crop:
  x_margin: 0.01 # margin as a proportion of the distance between x_points
  cropped_size: [ 640, 480 ]

points_of_interest:
- light_left
- sipper_left
- sipper_right
- light_right
- corner_UL
- corner_UR
- corner_LR
- corner_LL
